/**
 * Centralized validation limits for API parameters.
 */
export const VALIDATION_LIMITS = {
  // Pagination
  MAX_PAGE_LIMIT: 100,
  MIN_PAGE_LIMIT: 1,
  MIN_OFFSET: 0,

  // Arrays
  MAX_BULK_IDS: 100,
  MAX_REORDER_PROMPTS: 200,
  MAX_CHANNELS_PER_PUBLICATION: 50,
  MAX_SOURCE_TEXTS: 100,
  MAX_SELECTED_INDEXES: 100,
  MAX_REORDER_MEDIA: 100,

  // Strings (Names & Identifiers)
  MAX_NAME_LENGTH: 200,
  MAX_USERNAME_LENGTH: 100,
  MAX_CHANNEL_IDENTIFIER_LENGTH: 100,
  MAX_PROJECT_NAME_LENGTH: 200,
  MAX_TOKEN_NAME_LENGTH: 200,
  MAX_FILENAME_LENGTH: 255,

  // Strings (Descriptions & Content)
  MAX_DESCRIPTION_LENGTH: 2000,
  MAX_TITLE_LENGTH: 500,
  MAX_PUBLICATION_CONTENT_LENGTH: 100000,
  MAX_COMMENT_LENGTH: 10000,
  MAX_NOTE_LENGTH: 5000,
  MAX_TAGS_LENGTH: 1000,
  MAX_ALT_TEXT_LENGTH: 500,
  MAX_URL_LENGTH: 2000,

  // LLM & Translation
  MAX_LLM_MAX_TOKENS: 500000,
  MAX_LLM_PROMPT_LENGTH: 200000,
  MAX_LLM_CONTEXT_LENGTH: 20000,
  MAX_SOURCE_TEXT_CONTENT_LENGTH: 100000,
  MAX_TRANSLATE_TEXT_LENGTH: 200000,
  MAX_PROMPT_TEMPLATE_NAME_LENGTH: 200,
  MAX_PROMPT_TEMPLATE_PROMPT_LENGTH: 200000,

  // Auth
  MAX_AUTH_NAME_LENGTH: 100,

  // Numbers & Media
  MIN_ORDER: 0,
  MAX_ORDER: 1000000,
  MIN_MEDIA_SIZE_BYTES: 10,
};
